--CREATE TABLESPACE ANDERSONDB LOGGING DATAFILE 'C:\pronosticadorData\pronosticadorData.dbf' SIZE 512M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

--ALTER SESSION SET "_ORACLE_SCRIPT"=true;

--CREATE USER pronosticador PROFILE DEFAULT IDENTIFIED BY 8791110 DEFAULT TABLESPACE ANDERSONDB TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK;

--GRANT CONNECT TO pronosticador;

--GRANT RESOURCE TO pronosticador;

--ALTER USER pronosticador QUOTA UNLIMITED ON ANDERSONDB;

--SELECT * FROM DBA_USERS;